ALTER TABLE google_tokens ADD COLUMN sync_events INTEGER NOT NULL DEFAULT 1;
ALTER TABLE google_tokens ADD COLUMN sync_meals  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE google_tokens ADD COLUMN sync_bills  INTEGER NOT NULL DEFAULT 0;
